company_name: "QUIPUX SAS"
report_title: "RELACIÓN ENTREFA FACTURAS PROCESO DE COMPRAS A CONTABILIDAD {MONTH} {YEAR}"
filename_template: "Relación entrefa facturas_MES {MONTH}"
sheet_name: "RELACION FACTURAS ENVIADAS"
styles:
  header_bg_color: "4287f5"
  header_font_color: "FFFFFF"
  font_name: "Arial"
  font_size: 10
  border_style: "thin"
columns:
  - db_field: "fecha_admision_proveedor"
    label: "Fecha admisión factura del proveedor"
  - db_field: "medio_recepcion"
    label: "Medio en que se recibió"
  - db_field: "fecha_entrega_contabilidad"
    label: "Fecha entrega factura a contabilidad"
  - db_field: "nombre_recibe_contabilidad"
    label: "Nombre de quien recibe en contabilidad"
  - db_field: "nombre_proveedor"
    label: "Descripción"
  - db_field: "nit_proveedor"
    label: "NIT del proveedor"
  - db_field: "numero_factura"
    label: "No. Factura"
  - db_field: "forma_pago"
    label: "Forma de pago"
  - db_field: "acuso_recibido"
    label: "Acuso de recibido"
  - db_field: "recibido_bien_servicio"
    label: "Recibido de bien y/o servicio"
  - db_field: "aceptacion_empresa"
    label: "Aceptación empresa"
  - db_field: "recibido"
    label: "Recibido"
  - db_field: "observaciones_entrega"
    label: "Observaciones"
  - db_field: "eventos_dian_notif"
    label: "Eventos DIAN"
