company_name: "QUIPUX SAS"
report_title: "RELACIÓN ENTREFA FACTURAS PROCESO DE COMPRAS A CONTABILIDAD {MONTH} {YEAR}"
filename_template: "Relación entrefa facturas_MES {MONTH}"
sheet_name: "RELACION FACTURAS ENVIADAS"
styles:
  header_bg_color: "0070C0"
  header_font_color: "FFFFFF"
  font_name: "Aptos Narrow"
  font_size: 8
  border_style: "thin"
columns:
  - db_field: "fecha_admision_proveedor"
    label: "fecha emisión factura del proveedor"
  - db_field: "medio_recepcion"
    label: "medio en que se recibe"
  - db_field: "fecha_entrega_contabilidad"
    label: "fecha entrega factura a contabilidad"
  - db_field: "nombre_recibe_contabilidad"
    label: "nombre de quién recibe en contabilidad"
  - db_field: "nit_proveedor"
    label: "nit"
  - db_field: "nombre_proveedor"
    label: "descripcion"
  - db_field: "numero_factura"
    label: "no. factura"
  - db_field: "forma_pago"
    label: "forma de pago"
  - db_field: "acuso_recibido"
    label: "acuse de recibido"
  - db_field: "recibido_bien_servicio"
    label: "recibo de bien y/o servicio"
  - db_field: "aceptacion_expresa"
    label: "aceptacion expresa"
  - db_field: "observaciones_entrega"
    label: "observaciones"
  - db_field: "eventos_dian_notif"
    label: "evento dian"
