CREATE SCHEMA IF NOT EXISTS FACTURACION;

-- =========================
-- CATÁLOGOS (Tablas TIPO_...)
-- =========================

CREATE TABLE FACTURACION.TIPO_ESTADO_PROCESO (
    ID_ESTADO_PROCESO INT PRIMARY KEY,
    CODIGO_REFERENCIA VARCHAR(30) UNIQUE NOT NULL,
    DESCRIPCION       VARCHAR(150) NOT NULL
);

INSERT INTO FACTURACION.TIPO_ESTADO_PROCESO (ID_ESTADO_PROCESO, CODIGO_REFERENCIA, DESCRIPCION) VALUES
(1, 'PENDIENTE', 'Pendiente de procesamiento'),
(2, 'EN_PROCESO', 'En proceso de ingesta'),
(3, 'PROCESADO', 'Procesado de ingesta'),
(4, 'ERROR', 'Estado de error en el procesamiento'),
(5, 'FALLIDO', 'Estado de fallo definitivo (agotó reintentos)')
ON CONFLICT DO NOTHING;

CREATE TABLE FACTURACION.TIPO_ARCHIVO (
    ID_TIPO_ARCHIVO   INT PRIMARY KEY,
    CODIGO_REFERENCIA VARCHAR(30) UNIQUE NOT NULL,
    DESCRIPCION       VARCHAR(150) NOT NULL
);

INSERT INTO FACTURACION.TIPO_ARCHIVO (ID_TIPO_ARCHIVO, CODIGO_REFERENCIA, DESCRIPCION) VALUES
(1, 'ZIP', 'Archivo ZIP'),
(2, 'XML', 'Archivo XML'),
(3, 'PDF', 'Archivo PDF')
ON CONFLICT DO NOTHING;


CREATE TABLE FACTURACION.TIPO_PROCESO (
    ID_TIPO_PROCESO   INT PRIMARY KEY,
    CODIGO_REFERENCIA VARCHAR(50) UNIQUE NOT NULL,
    DESCRIPCION       VARCHAR(200) NOT NULL
);

INSERT INTO FACTURACION.TIPO_PROCESO (ID_TIPO_PROCESO, CODIGO_REFERENCIA, DESCRIPCION) VALUES
(1,  'ESCANEO_MALWARE',              'Verificación de archivos contra virus y malware'),
(2,  'DESCARGA_ALMACENAMIENTO',      'Descarga y almacenamiento del archivo en S3'),
(3,  'VALIDACION_CONTENIDO_ZIP',     'Verificación de que el ZIP contiene XML y PDF completos'),
(4,  'EXTRACCION_ZIP',               'Extracción de archivos del ZIP'),
(5,  'REGISTRO_ADJUNTOS',            'Registro de adjuntos en la base de datos'),
(6,  'VALIDACION_CUFE',              'Validación y extracción del CUFE'),
(7,  'VALIDACION_DENOMINACION',      'Validar denominación como factura electrónica de venta'),
(8,  'EXTRACCION_EMISOR',            'Extracción datos del vendedor/emisor'),
(9,  'EXTRACCION_ADQUIRIENTE',       'Extracción datos del adquiriente'),
(10, 'VALIDACION_NUMERACION',        'Validación de la numeración autorizada DIAN'),
(11, 'VALIDACION_FECHA_GENERACION',  'Validar fecha y hora de generación'),
(12, 'VALIDACION_FECHA_VALIDACION',  'Validar fecha y hora de validación/expedición DIAN'),
(13, 'VALIDACION_DOCUMENTO_DIAN',    'Validar documento «Documento validado por la DIAN»'),
(14, 'EXTRACCION_LINEAS',            'Extracción de líneas/ítems de la factura'),
(15, 'VALIDACION_VALOR_TOTAL',       'Validar valor total vs sumatoria de líneas'),
(16, 'EXTRACCION_FORMA_PAGO',        'Extracción de la forma de pago'),
(17, 'EXTRACCION_MEDIO_PAGO',        'Extracción del medio de pago'),
(18, 'EXTRACCION_CALIDAD_TRIBUTARIA','Extracción de la calidad tributaria del emisor'),
(19, 'EXTRACCION_IMPUESTOS',         'Extracción de impuestos a nivel factura'),
(20, 'VALIDACION_FIRMA_DIGITAL',     'Validación de la firma digital del facturador'),
(21, 'EXTRACCION_QR',                'Extracción y validación del código QR'),
(22, 'VALIDACION_ANEXO_TECNICO',     'Validación del anexo técnico UBL'),
(23, 'EXTRACCION_SOFTWARE',          'Extracción datos del software y proveedor tecnológico'),
(24, 'REGISTRO_FACTURA',             'Registro final de la factura en BD')
ON CONFLICT DO NOTHING;


CREATE TABLE FACTURACION.TIPO_ERROR (
    ID_TIPO_ERROR     INT PRIMARY KEY,
    CODIGO_REFERENCIA VARCHAR(50) UNIQUE NOT NULL,
    DESCRIPCION       VARCHAR(200) NOT NULL
);

INSERT INTO FACTURACION.TIPO_ERROR (ID_TIPO_ERROR, CODIGO_REFERENCIA, DESCRIPCION) VALUES
(1,  'MALWARE_DETECTADO',            'Se detectó virus o malware en el archivo'),
(2,  'EXTENSION_PROHIBIDA',          'El archivo tiene una extensión peligrosa (.exe, .bat, etc.)'),
(3,  'TAMANO_EXCEDIDO',              'El archivo excede el tamaño máximo permitido'),
(4,  'ZIP_CORRUPTO',                 'El archivo ZIP está corrupto o no es válido'),
(5,  'ZIP_SIN_XML',                  'El ZIP no contiene archivos XML de factura'),
(6,  'ZIP_PROFUNDIDAD_EXCEDIDA',     'ZIPs anidados exceden la profundidad máxima permitida'),
(7,  'ZIP_SUBZIP_INVALIDO',          'Un sub-ZIP dentro del ZIP principal no contiene pares válidos'),
(8,  'FALLO_DESCARGA_ADJUNTOS',      'No se pudieron descargar los adjuntos del correo'),
(9,  'FALLO_SUBIDA_S3',              'Error al subir el archivo a S3'),
(10, 'FALLO_REGISTRO_BD',            'Error al registrar el adjunto en la base de datos'),
(11, 'XML_EMBEBIDO_NO_ENCONTRADO',   'No se encontraron los XMLs de Invoice o ApplicationResponse embebidos'),
(12, 'XML_EMBEBIDO_PARSE_ERROR',     'Error al parsear el XML AttachedDocument para extraer embebidos'),
(13, 'PDF_FALTANTE',                 'No se encontró un PDF correspondiente al XML'),
(14, 'PDF_SIN_XML',                  'Se encontró un PDF sin XML correspondiente'),
(15, 'CORREO_SIN_ADJUNTOS_VALIDOS',  'El correo de facturación no contiene adjuntos válidos'),
(16, 'CORREO_RECHAZADO_FILTRO',      'El correo no cumple los criterios del filtro de facturación'),
(17, 'ERROR_PROCESAMIENTO_GENERAL',  'Error inesperado durante el procesamiento del correo'),
(18, 'ADJUNTO_DUPLICADO',            'El adjunto ya fue procesado previamente (hash duplicado)'),
(19, 'CUFE_NO_ENCONTRADO',           'No se encontró el CUFE en el XML'),
(20, 'CUFE_INVALIDO',                'El CUFE del XML no es válido o no coincide con el recalculado'),
(21, 'XML_PARSE_ERROR',              'Error al parsear el XML descargado de S3'),
(22, 'DATOS_EMISOR_INVALIDOS',       'No se pudieron extraer los datos del emisor'),
(23, 'DATOS_ADQUIRIENTE_INVALIDOS',  'No se pudieron extraer los datos del adquiriente'),
(24, 'NUMERACION_INVALIDA',          'La numeración de la factura no es válida'),
(25, 'FECHA_GENERACION_INVALIDA',    'Fecha de generación inválida o futura'),
(26, 'FECHA_VALIDACION_INVALIDA',    'Fecha de validación DIAN inválida'),
(27, 'VALIDACION_DIAN_FALLO',        'El documento no fue validado por la DIAN'),
(28, 'LINEAS_INVALIDAS',             'Las líneas de la factura no cumplen los requisitos'),
(29, 'VALOR_TOTAL_INCONSISTENTE',    'El valor total no coincide con la sumatoria de líneas'),
(30, 'FORMA_PAGO_INVALIDA',          'Forma de pago inválida o faltante'),
(31, 'MEDIO_PAGO_INVALIDO',          'Medio de pago inválido (requerido para pago de contado)'),
(32, 'CALIDAD_TRIBUTARIA_FALTANTE',  'No se informó la calidad tributaria del emisor'),
(33, 'IMPUESTOS_INVALIDOS',          'Impuestos con datos faltantes o inconsistentes'),
(34, 'FIRMA_DIGITAL_INVALIDA',       'La firma digital no es válida'),
(35, 'QR_INVALIDO',                  'El código QR es inválido o inconsistente'),
(36, 'ANEXO_TECNICO_INVALIDO',       'El XML no cumple con el anexo técnico UBL'),
(37, 'SOFTWARE_PROVEEDOR_FALTANTE',  'No se informó el fabricante de software'),
(38, 'ERROR_REGISTRO_FACTURA',       'Error al registrar la factura en la BD'),
(39, 'MAX_REINTENTOS_EXCEDIDO',      'Se excedió el máximo de reintentos')
ON CONFLICT DO NOTHING;


CREATE TABLE FACTURACION.TIPO_FORMA_PAGO (
    ID_FORMA_PAGO     INT PRIMARY KEY,
    CODIGO_REFERENCIA VARCHAR(20) UNIQUE NOT NULL,
    DESCRIPCION       VARCHAR(100) NOT NULL
);

INSERT INTO FACTURACION.TIPO_FORMA_PAGO (ID_FORMA_PAGO, CODIGO_REFERENCIA, DESCRIPCION) VALUES
(1, 'CONTADO', 'Contado'),
(2, 'CREDITO', 'Crédito')
ON CONFLICT DO NOTHING;


CREATE TABLE FACTURACION.TIPO_MEDIO_PAGO (
    ID_MEDIO_PAGO     INT PRIMARY KEY,
    CODIGO_REFERENCIA VARCHAR(30) UNIQUE NOT NULL,
    DESCRIPCION       VARCHAR(100) NOT NULL
);

INSERT INTO FACTURACION.TIPO_MEDIO_PAGO (ID_MEDIO_PAGO, CODIGO_REFERENCIA, DESCRIPCION) VALUES
(1, 'EFECTIVO', 'Efectivo'),
(2, 'TARJETA_CREDITO', 'Tarjeta crédito'),
(3, 'TARJETA_DEBITO', 'Tarjeta débito'),
(4, 'TRANSFERENCIA', 'Transferencia electrónica'),
(5, 'OTRO', 'Otro medio')
ON CONFLICT DO NOTHING;


CREATE TABLE FACTURACION.TIPO_IMPUESTO (
    ID_IMPUESTO       INT PRIMARY KEY,
    CODIGO_REFERENCIA VARCHAR(20) UNIQUE NOT NULL,
    DESCRIPCION       VARCHAR(150) NOT NULL
);

INSERT INTO FACTURACION.TIPO_IMPUESTO (ID_IMPUESTO, CODIGO_REFERENCIA, DESCRIPCION) VALUES
(1, 'IVA', 'Impuesto sobre las ventas'),
(2, 'INC', 'Impuesto nacional al consumo'),
(3, 'INC_BOLSAS', 'Impuesto nacional al consumo de bolsas plásticas')
ON CONFLICT DO NOTHING;


CREATE TABLE FACTURACION.TIPO_CONDICION_FISCAL (
    ID_CONDICION_FISCAL INT PRIMARY KEY,
    CODIGO_REFERENCIA   VARCHAR(40) UNIQUE NOT NULL,
    DESCRIPCION         VARCHAR(150) NOT NULL
);

INSERT INTO FACTURACION.TIPO_CONDICION_FISCAL (ID_CONDICION_FISCAL, CODIGO_REFERENCIA, DESCRIPCION) VALUES
(1, 'AGENTE_RETENEDOR_IVA', 'Agente retenedor de IVA'),
(2, 'AUTORRETENEDOR_RENTA', 'Autorretenedor de renta'),
(3, 'GRAN_CONTRIBUYENTE', 'Gran contribuyente'),
(4, 'SIMPLE', 'Contribuyente SIMPLE')
ON CONFLICT DO NOTHING;


CREATE TABLE FACTURACION.TIPO_ROL_TERCERO (
    ID_ROL_TERCERO    INT PRIMARY KEY,
    CODIGO_REFERENCIA VARCHAR(30) UNIQUE NOT NULL,
    DESCRIPCION       VARCHAR(100) NOT NULL
);

INSERT INTO FACTURACION.TIPO_ROL_TERCERO (ID_ROL_TERCERO, CODIGO_REFERENCIA, DESCRIPCION) VALUES
(1, 'EMISOR', 'Emisor / facturador'),
(2, 'ADQUIRIENTE', 'Adquiriente'),
(3, 'FABRICANTE_SOFTWARE', 'Fabricante de software'),
(4, 'PROVEEDOR_TECNOLOGICO', 'Proveedor tecnológico')
ON CONFLICT DO NOTHING;


-- Tipos de documento de identificación tributaria (Anexo 1.9 DIAN).
-- Códigos provienen del schemeName de cbc:CompanyID / sts:ProviderID.
CREATE TABLE FACTURACION.TIPO_DOCUMENTO_IDENTIDAD (
    ID_TIPO_DOCUMENTO   VARCHAR(2) PRIMARY KEY,
    CODIGO_REFERENCIA   VARCHAR(40) UNIQUE NOT NULL,
    DESCRIPCION         VARCHAR(120) NOT NULL
);

INSERT INTO FACTURACION.TIPO_DOCUMENTO_IDENTIDAD (ID_TIPO_DOCUMENTO, CODIGO_REFERENCIA, DESCRIPCION) VALUES
('11', 'REGISTRO_CIVIL',      'Registro civil'),
('12', 'TARJETA_IDENTIDAD',   'Tarjeta de identidad'),
('13', 'CEDULA_CIUDADANIA',   'Cédula de ciudadanía'),
('21', 'TARJETA_EXTRANJERIA', 'Tarjeta de extranjería'),
('22', 'CEDULA_EXTRANJERIA',  'Cédula de extranjería'),
('31', 'NIT',                 'NIT'),
('41', 'PASAPORTE',           'Pasaporte'),
('42', 'DOCUMENTO_EXTRANJERO','Documento de identificación extranjero'),
('47', 'PEP',                 'PEP (Permiso Especial de Permanencia)'),
('48', 'PPT',                 'PPT (Permiso Protección Temporal)'),
('50', 'NIT_OTRO_PAIS',       'NIT de otro país'),
('91', 'NUIP',                'NUIP')
ON CONFLICT DO NOTHING;

-- =========================
-- CORREO DE ENTRADA
-- =========================

CREATE TABLE FACTURACION.CORREO_ENTRANTE (
    CORREO_ID       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MESSAGE_ID      VARCHAR(255) NOT NULL UNIQUE,
    REMITENTE       VARCHAR(320) NOT NULL,
    ASUNTO          VARCHAR(500),
    PROCESADO       BOOLEAN NOT NULL DEFAULT FALSE,
    FECHA_DETECCION TIMESTAMPTZ NOT NULL,
    FECHA_ENVIO     TIMESTAMPTZ NULL,
    CUERPO_TEXTO    TEXT NULL,
    CUERPO_HTML     TEXT NULL,
    CONTIENE_ADJUNTOS BOOLEAN NOT NULL DEFAULT FALSE,
    ID_ORIGEN       INT NULL,
    OBSERVACION     VARCHAR(255) NULL
);

-- =========================
-- ADJUNTOS DEL CORREO
-- =========================

CREATE TABLE FACTURACION.ADJUNTOS_CORREO (
    ADJUNTO_ID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CORREO_ID          BIGINT NOT NULL REFERENCES FACTURACION.CORREO_ENTRANTE(CORREO_ID),
    ADJUNTO_PADRE_ID   BIGINT NULL REFERENCES FACTURACION.ADJUNTOS_CORREO(ADJUNTO_ID),
    NOMBRE_ARCHIVO     VARCHAR(255) NOT NULL,
    ID_TIPO_ARCHIVO    INT NULL,
    URI_ALMACENAMIENTO VARCHAR(255) NOT NULL,
    SHA256             VARCHAR(64) NOT NULL,
    ARCHIVO_SEGURO     BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT UQ_ADJUNTO_CORREO_NOMBRE UNIQUE (CORREO_ID, NOMBRE_ARCHIVO)
);

-- =========================
-- TRAZABILIDAD / ORQUESTACIÓN
-- =========================

CREATE TABLE FACTURACION.EVENTO_INGESTA (
    ADJUNTO_ID          BIGINT PRIMARY KEY REFERENCES FACTURACION.ADJUNTOS_CORREO(ADJUNTO_ID),
    FECHA_CREACION      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FECHA_ACTUALIZACION TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ID_ESTADO           INT NOT NULL REFERENCES FACTURACION.TIPO_ESTADO_PROCESO(ID_ESTADO_PROCESO),
    INTENTOS            BIGINT NOT NULL DEFAULT 0,
    VERSION_MOTOR       VARCHAR(10) NULL
);

CREATE TABLE FACTURACION.PROCESO_INGESTA (
    ID_PROCESO_INGESTA BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ADJUNTO_ID         BIGINT NOT NULL REFERENCES FACTURACION.ADJUNTOS_CORREO(ADJUNTO_ID),
    ID_PROCESO         INT NOT NULL REFERENCES FACTURACION.TIPO_PROCESO(ID_TIPO_PROCESO),
    ID_ESTADO          INT NOT NULL REFERENCES FACTURACION.TIPO_ESTADO_PROCESO(ID_ESTADO_PROCESO),
    ID_ERROR           INT NULL REFERENCES FACTURACION.TIPO_ERROR(ID_TIPO_ERROR),
    FECHA_INICIO       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FECHA_FIN          TIMESTAMPTZ NULL,
    OBSERVACION        VARCHAR(255) NOT NULL
);

-- =========================
-- TERCEROS (req_02: Emisor, req_03: Adquiriente)
-- =========================

CREATE TABLE FACTURACION.TERCERO (
    ID_TERCERO         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_ROL_TERCERO     INT NOT NULL REFERENCES FACTURACION.TIPO_ROL_TERCERO(ID_ROL_TERCERO),
    NUMERO_DOCUMENTO   VARCHAR(20) NOT NULL,
    DIGITO_VERIFICADOR VARCHAR(2) NULL,
    ID_TIPO_DOCUMENTO  VARCHAR(2) NULL REFERENCES FACTURACION.TIPO_DOCUMENTO_IDENTIDAD(ID_TIPO_DOCUMENTO),
    RAZON_SOCIAL       VARCHAR(300) NOT NULL,
    NOMBRE_COMERCIAL   VARCHAR(300) NULL,
    CORREO_CONTACTO    VARCHAR(320) NULL,
    TELEFONO_CONTACTO  VARCHAR(50) NULL,
    CODIGO_PAIS        CHAR(2) NOT NULL DEFAULT 'CO',
    FECHA_CREACION     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT UQ_TERCERO_DOCUMENTO_ROL UNIQUE (ID_ROL_TERCERO, NUMERO_DOCUMENTO)
);

CREATE INDEX IX_TERCERO_TIPO_DOCUMENTO ON FACTURACION.TERCERO (ID_TIPO_DOCUMENTO);

-- =========================
-- NUMERACIÓN AUTORIZADA DIAN (req_04)
-- =========================

CREATE TABLE FACTURACION.AUTORIZACION_NUMERACION_DIAN (
    ID_AUTORIZACION       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_TERCERO_EMISOR     BIGINT NOT NULL REFERENCES FACTURACION.TERCERO(ID_TERCERO),
    PREFIJO_FACTURACION   VARCHAR(20) NOT NULL DEFAULT '',
    NUMERO_RESOLUCION     VARCHAR(50) NOT NULL,
    RANGO_DESDE           BIGINT NOT NULL,
    RANGO_HASTA           BIGINT NOT NULL,
    FECHA_AUTORIZACION    DATE NOT NULL,
    FECHA_INICIO_VIGENCIA DATE NOT NULL,
    FECHA_FIN_VIGENCIA    DATE NOT NULL,
    CODIGO_TECNICO        VARCHAR(120) NULL,
    FECHA_CREACION        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT CK_RANGO_NUMERACION CHECK (RANGO_HASTA >= RANGO_DESDE),
    CONSTRAINT CK_VIGENCIA CHECK (FECHA_FIN_VIGENCIA >= FECHA_INICIO_VIGENCIA)
);

-- =========================
-- FACTURA (req_01, 04, 05, 09, 14, 15, 16)
-- =========================

CREATE TABLE FACTURACION.FACTURA (
    ID_FACTURA              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CUFE                    VARCHAR(100) NOT NULL,
    DENOMINACION            VARCHAR(50) NULL,
    PREFIJO_FACTURACION     VARCHAR(20) NOT NULL DEFAULT '',
    NUMERO_FACTURA          VARCHAR(50) NOT NULL,
    ID_TERCERO_EMISOR       BIGINT NOT NULL REFERENCES FACTURACION.TERCERO(ID_TERCERO),
    ID_TERCERO_ADQUIRIENTE  BIGINT NOT NULL REFERENCES FACTURACION.TERCERO(ID_TERCERO),
    ID_AUTORIZACION         BIGINT NULL REFERENCES FACTURACION.AUTORIZACION_NUMERACION_DIAN(ID_AUTORIZACION),
    FECHA_GENERACION        TIMESTAMPTZ NOT NULL,
    FECHA_EXPEDICION        TIMESTAMPTZ NULL,
    FECHA_VENCIMIENTO       DATE NULL,
    CODIGO_MONEDA           CHAR(3) NOT NULL DEFAULT 'COP',
    VALOR_TOTAL             NUMERIC(18,2) NULL CHECK (VALOR_TOTAL IS NULL OR VALOR_TOTAL >= 0),
    HASH_FIRMA_DIGITAL      VARCHAR(128) NULL,
    CONTENIDO_QR            TEXT NULL,
    ADJUNTO_ID              BIGINT NULL REFERENCES FACTURACION.ADJUNTOS_CORREO(ADJUNTO_ID),
    ID_ESTADO_PROCESO       INT NOT NULL REFERENCES FACTURACION.TIPO_ESTADO_PROCESO(ID_ESTADO_PROCESO),
    FECHA_CREACION          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FECHA_ACTUALIZACION     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT UQ_FACTURA_CUFE UNIQUE (CUFE),
    CONSTRAINT UQ_FACTURA_EMISOR_NUMERO UNIQUE (ID_TERCERO_EMISOR, PREFIJO_FACTURACION, NUMERO_FACTURA)
);

CREATE INDEX IX_FACTURA_ADQUIRIENTE ON FACTURACION.FACTURA (ID_TERCERO_ADQUIRIENTE);
CREATE INDEX IX_FACTURA_FECHA_EXPEDICION ON FACTURACION.FACTURA (FECHA_EXPEDICION);

-- =========================
-- CONDICIONES FISCALES DE LA FACTURA (req_12)
-- Múltiples registros por factura
-- =========================

CREATE TABLE FACTURACION.CONDICION_FISCAL_FACTURA (
    ID_FACTURA          BIGINT NOT NULL REFERENCES FACTURACION.FACTURA(ID_FACTURA),
    ID_CONDICION_FISCAL INT NOT NULL REFERENCES FACTURACION.TIPO_CONDICION_FISCAL(ID_CONDICION_FISCAL),
    ES_APLICABLE        BOOLEAN NOT NULL DEFAULT TRUE,
    NOTAS_ADICIONALES   VARCHAR(300) NULL,
    PRIMARY KEY (ID_FACTURA, ID_CONDICION_FISCAL)
);

-- =========================
-- FORMA Y MEDIO DE PAGO (req_10, req_11)
-- Un registro único por factura
-- =========================

CREATE TABLE FACTURACION.PAGO_FACTURA (
    ID_FACTURA        BIGINT PRIMARY KEY REFERENCES FACTURACION.FACTURA(ID_FACTURA),
    ID_FORMA_PAGO     INT NOT NULL REFERENCES FACTURACION.TIPO_FORMA_PAGO(ID_FORMA_PAGO),
    ID_MEDIO_PAGO     INT NULL REFERENCES FACTURACION.TIPO_MEDIO_PAGO(ID_MEDIO_PAGO),
    PLAZO_EN_DIAS     INTEGER NULL CHECK (PLAZO_EN_DIAS >= 0),
    NOTAS_ADICIONALES VARCHAR(300) NULL,
    CONSTRAINT CK_MEDIO_SI_CONTADO CHECK (
        (ID_FORMA_PAGO = 1 AND ID_MEDIO_PAGO IS NOT NULL)
        OR
        (ID_FORMA_PAGO = 2)
    )
);

-- =========================
-- DETALLE DE FACTURA / LÍNEAS (req_08)
-- Múltiples registros por factura
-- =========================

CREATE TABLE FACTURACION.DETALLE_FACTURA (
    ID_DETALLE        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_FACTURA        BIGINT NOT NULL REFERENCES FACTURACION.FACTURA(ID_FACTURA),
    NUMERO_LINEA      INTEGER NOT NULL,
    CODIGO_ITEM       VARCHAR(80) NULL,
    DESCRIPCION_ITEM  TEXT NOT NULL,
    CANTIDAD          NUMERIC(18,6) NOT NULL CHECK (CANTIDAD > 0),
    UNIDAD_DE_MEDIDA  VARCHAR(30) NULL,
    VALOR_UNITARIO    NUMERIC(18,2) NOT NULL CHECK (VALOR_UNITARIO >= 0),
    VALOR_TOTAL_LINEA NUMERIC(18,2) NOT NULL CHECK (VALOR_TOTAL_LINEA >= 0),
    CODIGO_INTERNO    VARCHAR(80) NULL,
    FECHA_CREACION    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT UQ_FACTURA_LINEA UNIQUE (ID_FACTURA, NUMERO_LINEA)
);

-- =========================
-- IMPUESTOS A NIVEL DETALLE/LÍNEA
-- Múltiples registros por línea
-- =========================

CREATE TABLE FACTURACION.IMPUESTO_DETALLE_FACTURA (
    ID_DETALLE     BIGINT NOT NULL REFERENCES FACTURACION.DETALLE_FACTURA(ID_DETALLE),
    ID_IMPUESTO    INT NOT NULL REFERENCES FACTURACION.TIPO_IMPUESTO(ID_IMPUESTO),
    TARIFA         NUMERIC(9,4) NOT NULL CHECK (TARIFA >= 0),
    BASE_GRAVABLE  NUMERIC(18,2) NOT NULL CHECK (BASE_GRAVABLE >= 0),
    VALOR_IMPUESTO NUMERIC(18,2) NOT NULL CHECK (VALOR_IMPUESTO >= 0),
    PRIMARY KEY (ID_DETALLE, ID_IMPUESTO, TARIFA)
);

-- =========================
-- IMPUESTOS A NIVEL FACTURA (req_13)
-- Múltiples registros por factura
-- =========================

CREATE TABLE FACTURACION.IMPUESTO_FACTURA (
    ID_FACTURA     BIGINT NOT NULL REFERENCES FACTURACION.FACTURA(ID_FACTURA),
    ID_IMPUESTO    INT NOT NULL REFERENCES FACTURACION.TIPO_IMPUESTO(ID_IMPUESTO),
    TARIFA         NUMERIC(9,4) NOT NULL CHECK (TARIFA >= 0),
    BASE_GRAVABLE  NUMERIC(18,2) NOT NULL CHECK (BASE_GRAVABLE >= 0),
    VALOR_IMPUESTO NUMERIC(18,2) NOT NULL CHECK (VALOR_IMPUESTO >= 0),
    PRIMARY KEY (ID_FACTURA, ID_IMPUESTO, TARIFA)
);

-- =========================
-- VALIDACIÓN DIAN (req_06, req_07)
-- Puede haber múltiples validaciones (reintentos)
-- =========================

CREATE TABLE FACTURACION.VALIDACION_DIAN (
    ID_VALIDACION              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_FACTURA                 BIGINT NOT NULL REFERENCES FACTURACION.FACTURA(ID_FACTURA),
    ID_PROCESO_INGESTA         BIGINT NULL REFERENCES FACTURACION.PROCESO_INGESTA(ID_PROCESO_INGESTA),
    FECHA_VALIDACION           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    IDENTIFICADOR_RASTREO      VARCHAR(120) NULL,
    CODIGO_RESPUESTA           VARCHAR(40) NULL,
    DESCRIPCION_RESPUESTA      VARCHAR(500) NULL,
    ID_ESTADO_PROCESO          INT NOT NULL REFERENCES FACTURACION.TIPO_ESTADO_PROCESO(ID_ESTADO_PROCESO),
    CUFE_VALIDADO              VARCHAR(100) NULL,
    CONTENIDO_QR_VALIDADO      TEXT NULL
);

-- =========================
-- FABRICANTE DE SOFTWARE (req_18)
-- =========================

CREATE TABLE FACTURACION.FABRICANTE_SOFTWARE (
    ID_FABRICANTE_SOFTWARE BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NUMERO_DOCUMENTO       VARCHAR(20) NOT NULL,
    RAZON_SOCIAL           VARCHAR(300) NOT NULL,
    FECHA_CREACION         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT UQ_SOFTWARE_FABRICANTE UNIQUE (NUMERO_DOCUMENTO)
);

-- =========================
-- PRODUCTO DE SOFTWARE (req_18)
-- =========================

CREATE TABLE FACTURACION.PRODUCTO_SOFTWARE (
    ID_PRODUCTO_SOFTWARE   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_FABRICANTE_SOFTWARE BIGINT NOT NULL REFERENCES FACTURACION.FABRICANTE_SOFTWARE(ID_FABRICANTE_SOFTWARE),
    NOMBRE_SOFTWARE        VARCHAR(250) NOT NULL,
    VERSION_SOFTWARE       VARCHAR(80) NULL,
    FECHA_CREACION         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX UQ_SOFTWARE_PRODUCTO ON FACTURACION.PRODUCTO_SOFTWARE (ID_FABRICANTE_SOFTWARE, NOMBRE_SOFTWARE, COALESCE(VERSION_SOFTWARE, ''));

-- =========================
-- SOFTWARE ↔ FACTURA (req_18)
-- Un registro único por factura
-- =========================

CREATE TABLE FACTURACION.SOFTWARE_FACTURA (
    ID_FACTURA               BIGINT PRIMARY KEY REFERENCES FACTURACION.FACTURA(ID_FACTURA),
    ID_PRODUCTO_SOFTWARE     BIGINT NOT NULL REFERENCES FACTURACION.PRODUCTO_SOFTWARE(ID_PRODUCTO_SOFTWARE),
    ID_PROVEEDOR_TECNOLOGICO BIGINT NULL REFERENCES FACTURACION.TERCERO(ID_TERCERO),
    NOTAS_ADICIONALES        VARCHAR(300) NULL
);

-- =========================
-- ÍNDICES DE APOYO
-- =========================

CREATE INDEX IX_CORREO_FECHA ON FACTURACION.CORREO_ENTRANTE (FECHA_DETECCION);
CREATE INDEX IX_ADJUNTO_CORREO ON FACTURACION.ADJUNTOS_CORREO (CORREO_ID);
CREATE INDEX IX_ADJUNTO_SHA256 ON FACTURACION.ADJUNTOS_CORREO (SHA256);
CREATE INDEX IX_PROCESO_ESTADO ON FACTURACION.PROCESO_INGESTA (ID_ESTADO);
CREATE INDEX IX_PROCESO_ADJUNTO ON FACTURACION.PROCESO_INGESTA (ADJUNTO_ID);
CREATE INDEX IX_VALIDACION_FACTURA ON FACTURACION.VALIDACION_DIAN (ID_FACTURA, FECHA_VALIDACION DESC);