CREATE SCHEMA IF NOT EXISTS FACTURACION;

-- =========================
-- CATÁLOGOS (Ahora "TIPO_...")
-- =========================

CREATE TABLE FACTURACION.TIPO_ESTADO_PROCESO (
    ID_ESTADO_PROCESO INT PRIMARY KEY,
    CODIGO_REFERENCIA VARCHAR(30) UNIQUE NOT NULL,
    DESCRIPCION       VARCHAR(150) NOT NULL
);

INSERT INTO FACTURACION.TIPO_ESTADO_PROCESO (ID_ESTADO_PROCESO, CODIGO_REFERENCIA, DESCRIPCION) VALUES
(1, 'RECIBIDO', 'Correo recibido'),
(2, 'ADJUNTO_VERIFICADO', 'Adjunto verificado'),
(3, 'ESCANEADO_OK', 'Archivo sin malware'),
(4, 'ESCANEADO_BLOQUEADO', 'Archivo con malware'),
(5, 'XML_EXTRAIDO', 'XML extraído'),
(6, 'FACTURA_PARSED', 'XML parseado'),
(7, 'VALIDADO_DIAN', 'Validado por DIAN'),
(8, 'RECHAZADO_DIAN', 'Rechazado por DIAN'),
(9, 'PERSISTIDO', 'Persistido en BD'),
(10, 'ERROR', 'Error en el proceso')
ON CONFLICT DO NOTHING;


CREATE TABLE FACTURACION.TIPO_FORMA_PAGO (
    ID_FORMA_PAGO     INT PRIMARY KEY,
    CODIGO_REFERENCIA VARCHAR(20) UNIQUE NOT NULL,
    DESCRIPCION       VARCHAR(100) NOT NULL
);

INSERT INTO FACTURACION.TIPO_FORMA_PAGO (ID_FORMA_PAGO, CODIGO_REFERENCIA, DESCRIPCION) VALUES
(1, 'CONTADO', 'Contado'),
(2, 'CREDITO', 'Crédito')
ON CONFLICT DO NOTHING;


CREATE TABLE FACTURACION.TIPO_MEDIO_PAGO (
    ID_MEDIO_PAGO     INT PRIMARY KEY,
    CODIGO_REFERENCIA VARCHAR(30) UNIQUE NOT NULL,
    DESCRIPCION       VARCHAR(100) NOT NULL
);

INSERT INTO FACTURACION.TIPO_MEDIO_PAGO (ID_MEDIO_PAGO, CODIGO_REFERENCIA, DESCRIPCION) VALUES
(1, 'EFECTIVO', 'Efectivo'),
(2, 'TARJETA_CREDITO', 'Tarjeta crédito'),
(3, 'TARJETA_DEBITO', 'Tarjeta débito'),
(4, 'TRANSFERENCIA', 'Transferencia electrónica'),
(5, 'OTRO', 'Otro medio')
ON CONFLICT DO NOTHING;


CREATE TABLE FACTURACION.TIPO_IMPUESTO (
    ID_IMPUESTO       INT PRIMARY KEY,
    CODIGO_REFERENCIA VARCHAR(20) UNIQUE NOT NULL,
    DESCRIPCION       VARCHAR(150) NOT NULL
);

INSERT INTO FACTURACION.TIPO_IMPUESTO (ID_IMPUESTO, CODIGO_REFERENCIA, DESCRIPCION) VALUES
(1, 'IVA', 'Impuesto sobre las ventas'),
(2, 'INC', 'Impuesto nacional al consumo'),
(3, 'INC_BOLSAS', 'Impuesto nacional al consumo de bolsas plásticas')
ON CONFLICT DO NOTHING;


CREATE TABLE FACTURACION.TIPO_CONDICION_FISCAL (
    ID_CONDICION_FISCAL INT PRIMARY KEY,
    CODIGO_REFERENCIA   VARCHAR(40) UNIQUE NOT NULL,
    DESCRIPCION         VARCHAR(150) NOT NULL
);

INSERT INTO FACTURACION.TIPO_CONDICION_FISCAL (ID_CONDICION_FISCAL, CODIGO_REFERENCIA, DESCRIPCION) VALUES
(1, 'AGENTE_RETENEDOR_IVA', 'Agente retenedor de IVA'),
(2, 'AUTORRETENEDOR_RENTA', 'Autorretenedor de renta'),
(3, 'GRAN_CONTRIBUYENTE', 'Gran contribuyente'),
(4, 'SIMPLE', 'Contribuyente SIMPLE')
ON CONFLICT DO NOTHING;


CREATE TABLE FACTURACION.TIPO_ROL_TERCERO (
    ID_ROL_TERCERO    INT PRIMARY KEY,
    CODIGO_REFERENCIA VARCHAR(30) UNIQUE NOT NULL,
    DESCRIPCION       VARCHAR(100) NOT NULL
);

INSERT INTO FACTURACION.TIPO_ROL_TERCERO (ID_ROL_TERCERO, CODIGO_REFERENCIA, DESCRIPCION) VALUES
(1, 'EMISOR', 'Emisor / facturador'),
(2, 'ADQUIRIENTE', 'Adquiriente'),
(3, 'FABRICANTE_SOFTWARE', 'Fabricante de software'),
(4, 'PROVEEDOR_TECNOLOGICO', 'Proveedor tecnológico')
ON CONFLICT DO NOTHING;

-- =========================
-- ARCHIVOS
-- =========================

CREATE TABLE FACTURACION.ARCHIVO (
    ID_ARCHIVO      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    URI_ALMACENAJE  TEXT NOT NULL,
    NOMBRE_ORIGINAL VARCHAR(255) NOT NULL,
    TIPO_MIME       VARCHAR(120) NOT NULL,
    HASH_SHA256     CHAR(64) NOT NULL UNIQUE,
    TAMANO_BYTES    BIGINT NOT NULL CHECK (TAMANO_BYTES >= 0),
    FECHA_CREACION  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================
-- CORREO DE ENTRADA
-- =========================

CREATE TABLE FACTURACION.CORREO_ENTRANTE (
    ID_CORREO        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_MENSAJE_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    REMITENTE        VARCHAR(320) NOT NULL,
    DESTINATARIO     VARCHAR(320) NOT NULL,
    ASUNTO           VARCHAR(500),
    FECHA_RECEPCION  TIMESTAMPTZ NOT NULL,
    FECHA_ENVIO      TIMESTAMPTZ NULL,
    CUERPO_TEXTO     TEXT NULL,
    CUERPO_HTML      TEXT NULL,
    ID_ARCHIVO_EML   BIGINT NULL REFERENCES FACTURACION.ARCHIVO(ID_ARCHIVO),
    FECHA_CREACION   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE FACTURACION.ADJUNTO_CORREO (
    ID_ADJUNTO          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CORREO           BIGINT NOT NULL REFERENCES FACTURACION.CORREO_ENTRANTE(ID_CORREO),
    ID_ARCHIVO          BIGINT NOT NULL REFERENCES FACTURACION.ARCHIVO(ID_ARCHIVO),
    NOMBRE_ARCHIVO      VARCHAR(255) NOT NULL,
    ORDEN_ADJUNTO       INTEGER NOT NULL DEFAULT 1,
    ES_FORMATO_ZIP      BOOLEAN NOT NULL DEFAULT FALSE,
    ES_FORMATO_XML      BOOLEAN NOT NULL DEFAULT FALSE,
    ES_COMPROBANTE_DIAN BOOLEAN NOT NULL DEFAULT FALSE,
    FECHA_CREACION      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT UQ_ADJUNTO_CORREO_ARCHIVO UNIQUE (ID_CORREO, ID_ARCHIVO)
);

-- =========================
-- TRAZABILIDAD / ORQUESTACIÓN
-- =========================

CREATE TABLE FACTURACION.PROCESO_INGESTA (
    ID_PROCESO         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CORREO          BIGINT NOT NULL REFERENCES FACTURACION.CORREO_ENTRANTE(ID_CORREO),
    ID_ADJUNTO         BIGINT NULL REFERENCES FACTURACION.ADJUNTO_CORREO(ID_ADJUNTO),
    ID_ARCHIVO_ORIGEN  BIGINT NULL REFERENCES FACTURACION.ARCHIVO(ID_ARCHIVO),
    CLAVE_IDEMPOTENCIA CHAR(64) NOT NULL UNIQUE,
    VERSION_MOTOR      VARCHAR(50) NOT NULL,
    ID_ESTADO_PROCESO  INT NOT NULL REFERENCES FACTURACION.TIPO_ESTADO_PROCESO(ID_ESTADO_PROCESO),
    CUFE_DETECTADO     VARCHAR(100) NULL,
    FECHA_INICIO       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FECHA_FIN          TIMESTAMPTZ NULL,
    RESUMEN_ERROR      TEXT NULL
);

CREATE TABLE FACTURACION.LOG_PROCESO (
    ID_LOG            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PROCESO        BIGINT NOT NULL REFERENCES FACTURACION.PROCESO_INGESTA(ID_PROCESO),
    NUMERO_SECUENCIA  INTEGER NOT NULL,
    CODIGO_ETAPA      VARCHAR(50) NOT NULL,
    ID_ESTADO_PROCESO INT NOT NULL REFERENCES FACTURACION.TIPO_ESTADO_PROCESO(ID_ESTADO_PROCESO),
    FECHA_INICIO      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FECHA_FIN         TIMESTAMPTZ NULL,
    DETALLE_JSON      JSONB NULL,
    DETALLE_ERROR     TEXT NULL,
    CONSTRAINT UQ_LOG_SECUENCIA UNIQUE (ID_PROCESO, NUMERO_SECUENCIA)
);

-- =========================
-- SEGURIDAD / MALWARE
-- =========================

CREATE TABLE FACTURACION.ESCANEO_SEGURIDAD (
    ID_ESCANEO         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_ARCHIVO         BIGINT NOT NULL REFERENCES FACTURACION.ARCHIVO(ID_ARCHIVO),
    MOTOR_ANTIVIRUS    VARCHAR(100) NOT NULL,
    VERSION_MOTOR      VARCHAR(50),
    FECHA_ESCANEO      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    MALWARE_DETECTADO  BOOLEAN NOT NULL DEFAULT FALSE,
    NIVEL_RIESGO       VARCHAR(30) NOT NULL DEFAULT 'BAJO',
    DETALLE_JSON       JSONB NULL
);

-- =========================
-- TERCEROS
-- =========================

CREATE TABLE FACTURACION.TERCERO (
    ID_TERCERO         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_ROL_TERCERO     INT NOT NULL REFERENCES FACTURACION.TIPO_ROL_TERCERO(ID_ROL_TERCERO),
    NUMERO_DOCUMENTO   VARCHAR(20) NOT NULL,
    DIGITO_VERIFICADOR VARCHAR(2) NULL,
    RAZON_SOCIAL       VARCHAR(300) NOT NULL,
    NOMBRE_COMERCIAL   VARCHAR(300) NULL,
    CORREO_CONTACTO    VARCHAR(320) NULL,
    TELEFONO_CONTACTO  VARCHAR(50) NULL,
    CODIGO_PAIS        CHAR(2) NOT NULL DEFAULT 'CO',
    FECHA_CREACION     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT UQ_TERCERO_DOCUMENTO_ROL UNIQUE (ID_ROL_TERCERO, NUMERO_DOCUMENTO)
);

-- =========================
-- NUMERACIÓN AUTORIZADA DIAN
-- =========================

CREATE TABLE FACTURACION.AUTORIZACION_NUMERACION_DIAN (
    ID_AUTORIZACION       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_TERCERO_EMISOR     BIGINT NOT NULL REFERENCES FACTURACION.TERCERO(ID_TERCERO),
    PREFIJO_FACTURACION   VARCHAR(20) NOT NULL DEFAULT '',
    NUMERO_RESOLUCION     VARCHAR(50) NOT NULL,
    RANGO_DESDE           BIGINT NOT NULL,
    RANGO_HASTA           BIGINT NOT NULL,
    FECHA_AUTORIZACION    DATE NOT NULL,
    FECHA_INICIO_VIGENCIA DATE NOT NULL,
    FECHA_FIN_VIGENCIA    DATE NOT NULL,
    CODIGO_TECNICO        VARCHAR(120) NULL,
    FECHA_CREACION        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT CK_RANGO_NUMERACION CHECK (RANGO_HASTA >= RANGO_DESDE),
    CONSTRAINT CK_VIGENCIA CHECK (FECHA_FIN_VIGENCIA >= FECHA_INICIO_VIGENCIA)
);

-- =========================
-- FACTURA
-- =========================

CREATE TABLE FACTURACION.FACTURA (
    ID_FACTURA                  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CUFE                        VARCHAR(100) NOT NULL,
    PREFIJO_FACTURACION         VARCHAR(20) NOT NULL DEFAULT '',
    NUMERO_FACTURA              VARCHAR(50) NOT NULL,
    ID_TERCERO_EMISOR           BIGINT NOT NULL REFERENCES FACTURACION.TERCERO(ID_TERCERO),
    ID_TERCERO_ADQUIRIENTE      BIGINT NOT NULL REFERENCES FACTURACION.TERCERO(ID_TERCERO),
    ID_AUTORIZACION             BIGINT NOT NULL REFERENCES FACTURACION.AUTORIZACION_NUMERACION_DIAN(ID_AUTORIZACION),
    FECHA_GENERACION            TIMESTAMPTZ NOT NULL,
    FECHA_EXPEDICION            TIMESTAMPTZ NOT NULL,
    FECHA_VENCIMIENTO           DATE NULL,
    CODIGO_MONEDA               CHAR(3) NOT NULL DEFAULT 'COP',
    VALOR_TOTAL                 NUMERIC(18,2) NOT NULL CHECK (VALOR_TOTAL >= 0),
    HASH_FIRMA_DIGITAL          VARCHAR(128) NULL,
    CONTENIDO_QR                TEXT NULL,
    ID_ARCHIVO_XML_ORIGEN       BIGINT NOT NULL REFERENCES FACTURACION.ARCHIVO(ID_ARCHIVO),
    ID_ARCHIVO_ZIP_ORIGEN       BIGINT NULL REFERENCES FACTURACION.ARCHIVO(ID_ARCHIVO),
    ID_ARCHIVO_COMPROBANTE_DIAN BIGINT NULL REFERENCES FACTURACION.ARCHIVO(ID_ARCHIVO),
    ID_ESTADO_PROCESO           INT NOT NULL REFERENCES FACTURACION.TIPO_ESTADO_PROCESO(ID_ESTADO_PROCESO),
    FECHA_CREACION              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FECHA_ACTUALIZACION         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT UQ_FACTURA_CUFE UNIQUE (CUFE),
    CONSTRAINT UQ_FACTURA_EMISOR_NUMERO UNIQUE (ID_TERCERO_EMISOR, PREFIJO_FACTURACION, NUMERO_FACTURA)
);

CREATE INDEX IX_FACTURA_ADQUIRIENTE ON FACTURACION.FACTURA (ID_TERCERO_ADQUIRIENTE);
CREATE INDEX IX_FACTURA_FECHA_EXPEDICION ON FACTURACION.FACTURA (FECHA_EXPEDICION);

-- =========================
-- CONDICIONES FISCALES DEL EMISOR EN LA FACTURA
-- =========================

CREATE TABLE FACTURACION.CONDICION_FISCAL_FACTURA (
    ID_FACTURA          BIGINT NOT NULL REFERENCES FACTURACION.FACTURA(ID_FACTURA),
    ID_CONDICION_FISCAL INT NOT NULL REFERENCES FACTURACION.TIPO_CONDICION_FISCAL(ID_CONDICION_FISCAL),
    ES_APLICABLE        BOOLEAN NOT NULL DEFAULT TRUE,
    NOTAS_ADICIONALES   VARCHAR(300) NULL,
    PRIMARY KEY (ID_FACTURA, ID_CONDICION_FISCAL)
);

-- =========================
-- FORMA Y MEDIO DE PAGO
-- =========================

CREATE TABLE FACTURACION.PAGO_FACTURA (
    ID_FACTURA        BIGINT PRIMARY KEY REFERENCES FACTURACION.FACTURA(ID_FACTURA),
    ID_FORMA_PAGO     INT NOT NULL REFERENCES FACTURACION.TIPO_FORMA_PAGO(ID_FORMA_PAGO),
    ID_MEDIO_PAGO     INT NULL REFERENCES FACTURACION.TIPO_MEDIO_PAGO(ID_MEDIO_PAGO),
    PLAZO_EN_DIAS     INTEGER NULL CHECK (PLAZO_EN_DIAS >= 0),
    NOTAS_ADICIONALES VARCHAR(300) NULL,
    CONSTRAINT CK_MEDIO_SI_CONTADO CHECK (
        -- Asumiendo que 1 es 'CONTADO' y 2 es 'CREDITO' según el catálogo insertado
        (ID_FORMA_PAGO = 1 AND ID_MEDIO_PAGO IS NOT NULL)
        OR
        (ID_FORMA_PAGO = 2)
    )
);

-- =========================
-- DETALLE DE FACTURA
-- =========================

CREATE TABLE FACTURACION.DETALLE_FACTURA (
    ID_DETALLE        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_FACTURA        BIGINT NOT NULL REFERENCES FACTURACION.FACTURA(ID_FACTURA),
    NUMERO_LINEA      INTEGER NOT NULL,
    CODIGO_ITEM       VARCHAR(80) NULL,
    DESCRIPCION_ITEM  TEXT NOT NULL,
    CANTIDAD          NUMERIC(18,6) NOT NULL CHECK (CANTIDAD > 0),
    UNIDAD_DE_MEDIDA  VARCHAR(30) NULL,
    VALOR_UNITARIO    NUMERIC(18,2) NOT NULL CHECK (VALOR_UNITARIO >= 0),
    VALOR_TOTAL_LINEA NUMERIC(18,2) NOT NULL CHECK (VALOR_TOTAL_LINEA >= 0),
    CODIGO_INTERNO    VARCHAR(80) NULL,
    FECHA_CREACION    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT UQ_FACTURA_LINEA UNIQUE (ID_FACTURA, NUMERO_LINEA)
);

CREATE TABLE FACTURACION.IMPUESTO_DETALLE_FACTURA (
    ID_DETALLE     BIGINT NOT NULL REFERENCES FACTURACION.DETALLE_FACTURA(ID_DETALLE),
    ID_IMPUESTO    INT NOT NULL REFERENCES FACTURACION.TIPO_IMPUESTO(ID_IMPUESTO),
    TARIFA         NUMERIC(9,4) NOT NULL CHECK (TARIFA >= 0),
    BASE_GRAVABLE  NUMERIC(18,2) NOT NULL CHECK (BASE_GRAVABLE >= 0),
    VALOR_IMPUESTO NUMERIC(18,2) NOT NULL CHECK (VALOR_IMPUESTO >= 0),
    PRIMARY KEY (ID_DETALLE, ID_IMPUESTO, TARIFA)
);

CREATE TABLE FACTURACION.IMPUESTO_FACTURA (
    ID_FACTURA     BIGINT NOT NULL REFERENCES FACTURACION.FACTURA(ID_FACTURA),
    ID_IMPUESTO    INT NOT NULL REFERENCES FACTURACION.TIPO_IMPUESTO(ID_IMPUESTO),
    TARIFA         NUMERIC(9,4) NOT NULL CHECK (TARIFA >= 0),
    BASE_GRAVABLE  NUMERIC(18,2) NOT NULL CHECK (BASE_GRAVABLE >= 0),
    VALOR_IMPUESTO NUMERIC(18,2) NOT NULL CHECK (VALOR_IMPUESTO >= 0),
    PRIMARY KEY (ID_FACTURA, ID_IMPUESTO, TARIFA)
);

-- =========================
-- VALIDACIÓN DIAN
-- =========================

CREATE TABLE FACTURACION.VALIDACION_DIAN (
    ID_VALIDACION              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_FACTURA                 BIGINT NOT NULL REFERENCES FACTURACION.FACTURA(ID_FACTURA),
    ID_PROCESO                 BIGINT NULL REFERENCES FACTURACION.PROCESO_INGESTA(ID_PROCESO),
    FECHA_VALIDACION           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    IDENTIFICADOR_RASTREO      VARCHAR(120) NULL,
    CODIGO_RESPUESTA           VARCHAR(40) NULL,
    DESCRIPCION_RESPUESTA      VARCHAR(500) NULL,
    ID_ESTADO_PROCESO          INT NOT NULL REFERENCES FACTURACION.TIPO_ESTADO_PROCESO(ID_ESTADO_PROCESO),
    CUFE_VALIDADO              VARCHAR(100) NULL,
    CONTENIDO_QR_VALIDADO      TEXT NULL,
    ID_ARCHIVO_RESPUESTA_XML   BIGINT NULL REFERENCES FACTURACION.ARCHIVO(ID_ARCHIVO),
    DETALLE_JSON               JSONB NULL
);

-- =========================
-- SOFTWARE
-- =========================

CREATE TABLE FACTURACION.FABRICANTE_SOFTWARE (
    ID_FABRICANTE_SOFTWARE BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NUMERO_DOCUMENTO       VARCHAR(20) NOT NULL,
    RAZON_SOCIAL           VARCHAR(300) NOT NULL,
    FECHA_CREACION         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT UQ_SOFTWARE_FABRICANTE UNIQUE (NUMERO_DOCUMENTO)
);

CREATE TABLE FACTURACION.PRODUCTO_SOFTWARE (
    ID_PRODUCTO_SOFTWARE   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_FABRICANTE_SOFTWARE BIGINT NOT NULL REFERENCES FACTURACION.FABRICANTE_SOFTWARE(ID_FABRICANTE_SOFTWARE),
    NOMBRE_SOFTWARE        VARCHAR(250) NOT NULL,
    VERSION_SOFTWARE       VARCHAR(80) NULL,
    FECHA_CREACION         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX UQ_SOFTWARE_PRODUCTO ON FACTURACION.PRODUCTO_SOFTWARE (ID_FABRICANTE_SOFTWARE, NOMBRE_SOFTWARE, COALESCE(VERSION_SOFTWARE, ''));

CREATE TABLE FACTURACION.SOFTWARE_FACTURA (
    ID_FACTURA               BIGINT PRIMARY KEY REFERENCES FACTURACION.FACTURA(ID_FACTURA),
    ID_PRODUCTO_SOFTWARE     BIGINT NOT NULL REFERENCES FACTURACION.PRODUCTO_SOFTWARE(ID_PRODUCTO_SOFTWARE),
    ID_PROVEEDOR_TECNOLOGICO BIGINT NULL REFERENCES FACTURACION.TERCERO(ID_TERCERO),
    NOTAS_ADICIONALES        VARCHAR(300) NULL
);

-- =========================
-- ÍNDICES DE APOYO
-- =========================

CREATE INDEX IX_ARCHIVO_SHA256 ON FACTURACION.ARCHIVO (HASH_SHA256);
CREATE INDEX IX_CORREO_FECHA ON FACTURACION.CORREO_ENTRANTE (FECHA_RECEPCION);
CREATE INDEX IX_PROCESO_ESTADO ON FACTURACION.PROCESO_INGESTA (ID_ESTADO_PROCESO);
CREATE INDEX IX_VALIDACION_FACTURA ON FACTURACION.VALIDACION_DIAN (ID_FACTURA, FECHA_VALIDACION DESC);