-- =========================
-- TABLA DE DEVOLUCIONES
-- =========================

CREATE TABLE IF NOT EXISTS FACTURACION.DEVOLUCION (
    ID_DEVOLUCION       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CORREO_ID           BIGINT NOT NULL REFERENCES FACTURACION.CORREO_ENTRANTE(CORREO_ID),
    FECHA_DEVOLUCION    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    REMITENTE_ORIGINAL  VARCHAR(320) NOT NULL,
    DESTINATARIO_NOTIF  VARCHAR(320) NOT NULL, -- Correo del proveedor
    ASUNTO_ORIGINAL     VARCHAR(500),
    MOTIVO_PRINCIPAL    TEXT NOT NULL,
    INCONSISTENCIAS_JSON JSONB,
    ESTADO_NOTIFICACION VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE', -- PENDIENTE, ENVIADO, FALLIDO
    INTENTOS_ENVIO      INT NOT NULL DEFAULT 0,
    ERROR_ENVIO         TEXT,
    FECHA_CREACION      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS IX_DEVOLUCION_CORREO ON FACTURACION.DEVOLUCION (CORREO_ID);
CREATE INDEX IF NOT EXISTS IX_DEVOLUCION_ESTADO ON FACTURACION.DEVOLUCION (ESTADO_NOTIFICACION);
